// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ise_SLa40TtLPknDf4seXEO8iwqm8wQ',
    appId: '1:927719778971:web:90102b415d6ae0c2e5b43e',
    messagingSenderId: '927719778971',
    projectId: 'mlritattendancesystem',
    authDomain: 'mlritattendancesystem.firebaseapp.com',
    storageBucket: 'mlritattendancesystem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_AOgfaCaUwlY7ntpWBO9FDuNkmTlaKQ8',
    appId: '1:927719778971:android:6b2c6c7ce65c006fe5b43e',
    messagingSenderId: '927719778971',
    projectId: 'mlritattendancesystem',
    storageBucket: 'mlritattendancesystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVrGEVpDECL3CAnc2y-S3SvgPUmSfkFkc',
    appId: '1:927719778971:ios:a74080cd7d78997ae5b43e',
    messagingSenderId: '927719778971',
    projectId: 'mlritattendancesystem',
    storageBucket: 'mlritattendancesystem.firebasestorage.app',
    iosBundleId: 'com.example.hodWebDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVrGEVpDECL3CAnc2y-S3SvgPUmSfkFkc',
    appId: '1:927719778971:ios:a74080cd7d78997ae5b43e',
    messagingSenderId: '927719778971',
    projectId: 'mlritattendancesystem',
    storageBucket: 'mlritattendancesystem.firebasestorage.app',
    iosBundleId: 'com.example.hodWebDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ise_SLa40TtLPknDf4seXEO8iwqm8wQ',
    appId: '1:927719778971:web:742f94ae040fb713e5b43e',
    messagingSenderId: '927719778971',
    projectId: 'mlritattendancesystem',
    authDomain: 'mlritattendancesystem.firebaseapp.com',
    storageBucket: 'mlritattendancesystem.firebasestorage.app',
  );
}
